### ISSUE TITLE
Fix Iconv issue

### ISSUE THREAD

**Issue by ferventcoder** [msutter/puppet-dsc#3]
```
rob@skylight:~/code/puppetlabs/modules/puppet-dsc [master] 12:40:04 $ bundle exec rake --trace
rake aborted!
LoadError: cannot load such file -- iconv
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/mof-b325b90d430e/lib/mof/scanner.rb:22:in `require'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/mof-b325b90d430e/lib/mof/scanner.rb:22:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/mof-b325b90d430e/lib/mof/parser.rb:17:in `require'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/mof-b325b90d430e/lib/mof/parser.rb:17:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/mof-b325b90d430e/lib/mof.rb:8:in `require'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/mof-b325b90d430e/lib/mof.rb:8:in `<module:MOF>'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/mof-b325b90d430e/lib/mof.rb:7:in `<top (required)>'
/Users/rob/code/puppetlabs/MODULES/puppet-dsc/build/dsc.rb:7:in `require'
/Users/rob/code/puppetlabs/MODULES/puppet-dsc/build/dsc.rb:7:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/default_loader.rb:10:in `load'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:767:in `load_imports'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:697:in `raw_load_rakefile'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.5/bin/rake:23:in `load'
/opt/boxen/rbenv/versions/2.1.5/bin/rake:23:in `<main>'
```

**Comment by ferventcoder** [comment]
Actually this is in the mof repo.
